-- CONSULTA OLAP
SELECT COUNT(*) FROM [fato].[OLAP_ATENDIMENTO] A 
LEFT JOIN [dim].[OLAP_PACIENTE] B ON A.SK_PACIENTE = B.SK_PACIENTE
LEFT JOIN [dim].[OLAP_CIDADE] C ON B.SK_CIDADE = C.SK_CIDADE
WHERE CIDADE = 'Londres'

-- CONSULTA OLTP
SELECT COUNT(*) FROM [tmp].[OLTP_ATENDIMENTO] A
LEFT JOIN [tmp].[OLTP_PACIENTE] B ON A.PACIENTE = B.NOME
WHERE B.CIDADE = 'Harrogate'
