-- CONSULTA 1 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT TOP 1
	A.ID_ATENDIMENTO
	, PRI.PRIORIDADE
	, TP.TIPO
	, PAC.NOME AS 'PACIENTE'
	, PAC.SEXO
	, TEM2.DATA AS 'NASCIMENTO'
	, PAC.EMAIL
	, CIT.CIDADE AS 'CIDADE_PAC'
	, DEN.NOME AS 'DENTISTA'
	, DEN.SEXO
	, DEN.CREDENCIAL
	, ESP.ESPECIALIDADE
	, TEM.DATA AS 'DATA_CONSULT'
	, A.HORA_INICIO
	, A.HORA_FIM
	, A.FATURA
FROM [fato].[OLAP_ATENDIMENTO] A
LEFT JOIN [dim].[OLAP_PRIORIDADE] PRI ON A.SK_PRIORIDADE = PRI.SK_PRIORIDADE
LEFT JOIN [dim].[OLAP_TIPO] TP ON A.SK_TIPO = TP.SK_TIPO
LEFT JOIN [dim].[OLAP_PACIENTE] PAC ON A.SK_PACIENTE = PAC.SK_PACIENTE
LEFT JOIN [dim].[OLAP_CIDADE] CIT ON PAC.SK_CIDADE = CIT.SK_CIDADE
LEFT JOIN [dim].[OLAP_DENTISTA] DEN ON A.SK_DENTISTA = DEN.SK_DENTISTA
LEFT JOIN [dim].[OLAP_ESPECIALIDADE] ESP ON DEN.SK_ESPECIALIDADE = ESP.SK_ESPECIALIDADE
LEFT JOIN [dim].[OLAP_TEMPO] TEM ON A.DATA = TEM.SK_DATA
LEFT JOIN [dim].[OLAP_TEMPO] TEM2 ON PAC.NASCIMENTO = TEM2.SK_DATA
ORDER BY NEWID() -- ORDENA ALEATORIAMENTE
SET STATISTICS TIME OFF

-- CONSULTA 2 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT
	A.ID_ATENDIMENTO
	, PRI.PRIORIDADE
	, TP.TIPO
	, PAC.NOME AS 'PACIENTE'
	, PAC.SEXO
	, TEM2.DATA AS 'NASCIMENTO'
	, PAC.EMAIL
	, CIT.CIDADE AS 'CIDADE_PAC'
	, DEN.NOME AS 'DENTISTA'
	, DEN.SEXO
	, DEN.CREDENCIAL
	, ESP.ESPECIALIDADE
	, TEM.DATA AS 'DATA_CONSULT'
	, A.HORA_INICIO
	, A.HORA_FIM
	, A.FATURA
FROM [fato].[OLAP_ATENDIMENTO] A
LEFT JOIN [dim].[OLAP_PRIORIDADE] PRI ON A.SK_PRIORIDADE = PRI.SK_PRIORIDADE
LEFT JOIN [dim].[OLAP_TIPO] TP ON A.SK_TIPO = TP.SK_TIPO
LEFT JOIN [dim].[OLAP_PACIENTE] PAC ON A.SK_PACIENTE = PAC.SK_PACIENTE
LEFT JOIN [dim].[OLAP_CIDADE] CIT ON PAC.SK_CIDADE = CIT.SK_CIDADE
LEFT JOIN [dim].[OLAP_DENTISTA] DEN ON A.SK_DENTISTA = DEN.SK_DENTISTA
LEFT JOIN [dim].[OLAP_ESPECIALIDADE] ESP ON DEN.SK_ESPECIALIDADE = ESP.SK_ESPECIALIDADE
LEFT JOIN [dim].[OLAP_TEMPO] TEM ON A.DATA = TEM.SK_DATA
LEFT JOIN [dim].[OLAP_TEMPO] TEM2 ON PAC.NASCIMENTO = TEM2.SK_DATA
ORDER BY A.ID_ATENDIMENTO
SET STATISTICS TIME OFF

-- CONSULTA 3 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	CD.CIDADE, 
	COUNT(*) AS 'QTD'
FROM [fato].[OLAP_ATENDIMENTO] AT
LEFT JOIN [dim].[OLAP_PACIENTE] PC ON AT.SK_PACIENTE = PC.SK_PACIENTE
LEFT JOIN [dim].[OLAP_CIDADE] CD ON PC.SK_CIDADE = CD.SK_CIDADE
GROUP BY CD.CIDADE
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 4 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	CD.CIDADE, 
	SUM(AT.FATURA) AS 'FATURAMENTO'
FROM [fato].[OLAP_ATENDIMENTO] AT
LEFT JOIN [dim].[OLAP_PACIENTE] PC ON AT.SK_PACIENTE = PC.SK_PACIENTE
LEFT JOIN [dim].[OLAP_CIDADE] CD ON PC.SK_CIDADE = CD.SK_CIDADE
GROUP BY CD.CIDADE
ORDER BY 'FATURAMENTO' DESC
SET STATISTICS TIME OFF

-- CONSULTA 5 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	PR.PRIORIDADE, 
	COUNT(*) AS 'QTD'
FROM [fato].[OLAP_ATENDIMENTO] AT
LEFT JOIN [dim].[OLAP_PRIORIDADE] PR ON AT.SK_PRIORIDADE = PR.SK_PRIORIDADE
GROUP BY PR.PRIORIDADE
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 6 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	DT.NOME, 
	COUNT(*) AS 'QTD'
FROM [fato].[OLAP_ATENDIMENTO] AT
LEFT JOIN [dim].[OLAP_DENTISTA] DT ON AT.SK_DENTISTA = DT.SK_DENTISTA
GROUP BY DT.NOME
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 7 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	ES.ESPECIALIDADE, 
	COUNT(*) AS 'QTD'
FROM [fato].[OLAP_ATENDIMENTO] AT
LEFT JOIN [dim].[OLAP_DENTISTA] DT ON AT.SK_DENTISTA = DT.SK_DENTISTA
LEFT JOIN [dim].[OLAP_ESPECIALIDADE] ES ON DT.SK_ESPECIALIDADE = ES.SK_ESPECIALIDADE
GROUP BY ES.ESPECIALIDADE
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 8 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	TP.MES, 
	COUNT(*) AS 'QTD'
FROM [fato].[OLAP_ATENDIMENTO] AT
LEFT JOIN [dim].[OLAP_TEMPO] TP ON AT.DATA = TP.SK_DATA
GROUP BY TP.MES
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 9 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	PC.SEXO, 
	COUNT(*),
	SUM(AT.FATURA) AS 'FATURAMENTO'
FROM [fato].[OLAP_ATENDIMENTO] AT
LEFT JOIN [dim].[OLAP_PACIENTE] PC ON AT.SK_PACIENTE = PC.SK_PACIENTE
GROUP BY PC.SEXO
ORDER BY 'FATURAMENTO' DESC
SET STATISTICS TIME OFF

-- CONSULTA 10 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	FLOOR(DATEDIFF(DAY, CAST(TP.DATA AS DATE), CAST(GETDATE() AS DATE)) / 365.25) AS 'IDADE'
	, SUM(1) AS 'QTD'
FROM [dim].[OLAP_PACIENTE] PC
LEFT JOIN [dim].[OLAP_TEMPO] TP ON PC.NASCIMENTO = TP.SK_DATA
GROUP BY FLOOR(DATEDIFF(DAY, CAST(TP.DATA AS DATE), CAST(GETDATE() AS DATE)) / 365.25)
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 11 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT T.TIPO
	, COUNT(*) AS QTD_ATENDIMENTO 
FROM [fato].[OLAP_ATENDIMENTO] A
LEFT JOIN [dim].[OLAP_PACIENTE] P ON A.SK_PACIENTE = P.SK_PACIENTE
LEFT JOIN [dim].[OLAP_TIPO] T ON A.SK_TIPO = T.SK_TIPO
WHERE P.SEXO = 'M' and A.FATURA >= 20 and A.FATURA <= 85
GROUP BY T.TIPO
ORDER BY QTD_ATENDIMENTO DESC
SET STATISTICS TIME OFF

-- CONSULTA 12 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT T.TIPO
	, COUNT(*) AS QTD_ATENDIMENTO 
FROM [fato].[OLAP_ATENDIMENTO] A
LEFT JOIN [dim].[OLAP_PACIENTE] P ON A.SK_PACIENTE = P.SK_PACIENTE
LEFT JOIN [dim].[OLAP_TIPO] T ON A.SK_TIPO = T.SK_TIPO
WHERE P.SEXO = 'M' and A.FATURA = 45 or A.FATURA = 46
GROUP BY T.TIPO
ORDER BY QTD_ATENDIMENTO DESC
SET STATISTICS TIME OFF

-- CONSULTA 13 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT T.TIPO
	, COUNT(*) AS QTD_ATENDIMENTO 
FROM [fato].[OLAP_ATENDIMENTO] A
LEFT JOIN [dim].[OLAP_PACIENTE] P ON A.SK_PACIENTE = P.SK_PACIENTE
LEFT JOIN [dim].[OLAP_TIPO] T ON A.SK_TIPO = T.SK_TIPO
WHERE P.SEXO = 'M' and A.FATURA > 44 and A.FATURA < 47
GROUP BY T.TIPO
ORDER BY QTD_ATENDIMENTO DESC
SET STATISTICS TIME OFF

-- CONSULTA 14 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT P.NOME
	, C.CIDADE AS CIDADE_PACIENTE
	, D.NOME, E.ESPECIALIDADE AS ESPECIALIDADE_DENTISTA 
FROM [fato].[OLAP_ATENDIMENTO] A
LEFT JOIN [dim].[OLAP_PACIENTE] P ON A.SK_PACIENTE = P.SK_PACIENTE
LEFT JOIN [dim].[OLAP_CIDADE] C ON P.SK_CIDADE = C.SK_CIDADE
LEFT JOIN [dim].[OLAP_DENTISTA] D ON A.SK_DENTISTA = D.SK_DENTISTA
LEFT JOIN [dim].[OLAP_ESPECIALIDADE] E ON E.SK_ESPECIALIDADE = D.SK_ESPECIALIDADE
WHERE E.ESPECIALIDADE like 'Ortodontia'
SET STATISTICS TIME OFF