-- CONSULTA 1 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT TOP 1
	A.[ID_ATENDIMENTO]
	, B.[PRIORIDADE]
	, C.[TIPO]
	, A.PACIENTE
	, D.SEXO
	, D.NASCIMENTO
	, D.EMAIL
	, D.CIDADE 'CIDADE_PAC'
	, E.NOME 'DENTISTA'
	, E.SEXO
	, E.CREDENCIAL
	, E.ESPECIALIDADE
	, F.DATA 'DATA_CONSULT'
	, F.HORA_INICIO
	, F.HORA_FIM
	, A.FATURA
FROM [tmp].[OLTP_ATENDIMENTO] A
LEFT JOIN [tmp].[OLTP_PRIORIDAD] B ON A.ID_ATENDIMENTO = B.ID_ATENDIMENTO
LEFT JOIN [tmp].[OLTP_TIP] C ON A.ID_ATENDIMENTO = C.ID_ATENDIMENTO
LEFT JOIN [tmp].[OLTP_PACIENTE] D ON A.PACIENTE = D.NOME
LEFT JOIN [tmp].[OLTP_DENTISTA] E ON A.DENTISTA = E.NOME
LEFT JOIN [tmp].[OLTP_TEMPO] F ON A.ID_ATENDIMENTO = F.ID_ATENDIMENTO
ORDER BY NEWID() -- ORDENA ALEATORIAMENTE
SET STATISTICS TIME OFF

-- CONSULTA 2 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT
	A.[ID_ATENDIMENTO]
	, B.[PRIORIDADE]
	, C.[TIPO]
	, A.PACIENTE
	, D.SEXO
	, D.NASCIMENTO
	, D.EMAIL
	, D.CIDADE 'CIDADE_PAC'
	, E.NOME 'DENTISTA'
	, E.SEXO
	, E.CREDENCIAL
	, E.ESPECIALIDADE
	, F.DATA 'DATA_CONSULT'
	, F.HORA_INICIO
	, F.HORA_FIM
	, A.FATURA
FROM [tmp].[OLTP_ATENDIMENTO] A
LEFT JOIN [tmp].[OLTP_PRIORIDAD] B ON A.ID_ATENDIMENTO = B.ID_ATENDIMENTO
LEFT JOIN [tmp].[OLTP_TIP] C ON A.ID_ATENDIMENTO = C.ID_ATENDIMENTO
LEFT JOIN [tmp].[OLTP_PACIENTE] D ON A.PACIENTE = D.NOME
LEFT JOIN [tmp].[OLTP_DENTISTA] E ON A.DENTISTA = E.NOME
LEFT JOIN [tmp].[OLTP_TEMPO] F ON A.ID_ATENDIMENTO = F.ID_ATENDIMENTO
ORDER BY A.ID_ATENDIMENTO
SET STATISTICS TIME OFF

-- CONSULTA 3 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	PC.CIDADE, 
	COUNT(*) AS 'QTD'
FROM [tmp].[OLTP_ATENDIMENTO] AT
LEFT JOIN [tmp].[OLTP_PACIENTE] PC ON AT.PACIENTE = PC.NOME
GROUP BY PC.CIDADE
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 4 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	PC.CIDADE, 
	SUM(AT.FATURA) AS 'FATURAMENTO'
FROM [tmp].[OLTP_ATENDIMENTO] AT
LEFT JOIN [tmp].[OLTP_PACIENTE] PC ON AT.PACIENTE = PC.NOME
GROUP BY PC.CIDADE
ORDER BY 'FATURAMENTO' DESC
SET STATISTICS TIME OFF

-- CONSULTA 5 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	PR.PRIORIDADE, 
	COUNT(*) AS 'QTD'
FROM [tmp].[OLTP_ATENDIMENTO] AT
LEFT JOIN [tmp].[OLTP_PRIORIDAD] PR ON AT.ID_ATENDIMENTO = PR.ID_ATENDIMENTO
GROUP BY PR.PRIORIDADE
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 6 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	DT.NOME, 
	COUNT(*) AS 'QTD'
FROM [tmp].[OLTP_ATENDIMENTO] AT
LEFT JOIN [tmp].[OLTP_DENTISTA] DT ON AT.DENTISTA = DT.NOME
GROUP BY DT.NOME
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 7 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	DT.ESPECIALIDADE, 
	COUNT(*) AS 'QTD'
FROM [tmp].[OLTP_ATENDIMENTO] AT
LEFT JOIN [tmp].[OLTP_DENTISTA] DT ON AT.DENTISTA = DT.NOME
GROUP BY DT.ESPECIALIDADE
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 8 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	MONTH(TP.DATA) AS 'MES', 
	COUNT(*) AS 'QTD'
FROM [tmp].[OLTP_ATENDIMENTO] AT
LEFT JOIN [tmp].[OLTP_TEMPO] TP ON AT.ID_ATENDIMENTO = TP.ID_ATENDIMENTO
GROUP BY MONTH(TP.DATA)
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 9 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	PC.SEXO, 
	COUNT(*),
	SUM(AT.FATURA) AS 'FATURAMENTO'
FROM [tmp].[OLTP_ATENDIMENTO] AT
LEFT JOIN [tmp].[OLTP_PACIENTE] PC ON AT.PACIENTE = PC.NOME
GROUP BY PC.SEXO
ORDER BY 'FATURAMENTO' DESC
SET STATISTICS TIME OFF

-- CONSULTA 10 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT 
	FLOOR(DATEDIFF(DAY, CAST(PC.NASCIMENTO AS DATE), CAST(GETDATE() AS DATE)) / 365.25) AS 'IDADE'
	, SUM(1) AS 'QTD'
FROM [tmp].[OLTP_PACIENTE] PC
GROUP BY FLOOR(DATEDIFF(DAY, CAST(PC.NASCIMENTO AS DATE), CAST(GETDATE() AS DATE)) / 365.25)
ORDER BY 'QTD' DESC
SET STATISTICS TIME OFF

-- CONSULTA 11 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT T.TIPO
	, COUNT(*) AS QTD_ATENDIMENTO 
FROM [tmp].[OLTP_ATENDIMENTO] A
LEFT JOIN [tmp].[OLTP_PACIENTE] P ON A.PACIENTE = P.NOME
LEFT JOIN [tmp].[OLTP_TIP] T ON A.ID_ATENDIMENTO = T.ID_ATENDIMENTO
WHERE P.SEXO = 'M' and A.FATURA >= 20 and A.FATURA <= 85
GROUP BY T.TIPO
ORDER BY QTD_ATENDIMENTO DESC
SET STATISTICS TIME OFF

-- CONSULTA 12 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT T.TIPO
	, COUNT(*) AS QTD_ATENDIMENTO 
FROM [tmp].[oltp_ATENDIMENTO] A
LEFT JOIN [tmp].[oltp_PACIENTE] P ON A.PACIENTE = P.NOME
LEFT JOIN [tmp].[oltp_TIP] T ON A.ID_ATENDIMENTO = T.ID_ATENDIMENTO
WHERE P.SEXO = 'M' and A.FATURA = 45 or A.FATURA = 46
GROUP BY T.TIPO
ORDER BY QTD_ATENDIMENTO DESC
SET STATISTICS TIME OFF

-- CONSULTA 13 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT T.TIPO
	, COUNT(*) AS QTD_ATENDIMENTO 
FROM [tmp].[OLTP_ATENDIMENTO] A
LEFT JOIN [tmp].[OTLP_PACIENTE] P ON A.PACIENTE = P.NOME
LEFT JOIN [tmp].[OLTP_TIP] T ON A.ID_ATENDIMENTO = T.ID_ATENDIMENTO
WHERE P.SEXO = 'M' and A.FATURA > 44 and A.FATURA < 47
GROUP BY T.TIPO
ORDER BY QTD_ATENDIMENTO DESC
SET STATISTICS TIME OFF

-- CONSULTA 14 ##########################################################################################
DBCC DROPCLEANBUFFERS
SET STATISTICS TIME ON
SELECT P.NOME
	, CIDADE AS CIDADE_PACIENTE
	, D.NOME, ESPECIALIDADE AS ESPECIALIDADE_DENTISTA 
FROM [tmp].[OLTP_ATENDIMENTO] A
LEFT JOIN [tmp].[OLTP_PACIENTE] P ON A.PACIENTE = P.NOME
LEFT JOIN [tmp].[OLTP_DENTISTA] D ON A.DENTISTA = D.NOME
WHERE ESPECIALIDADE like 'Ortodontia'
SET STATISTICS TIME OFF